language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3.24
  - 7.4

sudo: false
dist: trusty

env:
  matrix:
    - NETCOMMONS_VERSION=master DB=mysql
  global:
    - secure: "eOJhJHrLG6nQUX222m/g/g1LR+k/W/mtdvJsxyHRx++Robu6EIDuXmE6Y4SuIi0vlvJbdhrOx9Gu0oKIkX5RYXbY0iwFnoQ1iXYnPBH9DoBp7ucr2ddd/UDsIkR40k6v8m2Dunzzk1xfiZvXw0UUxL/ulMQLBqvjEZu+pgLM9sc="
    - GIT_COMMITTER_NAME=s-nakajima
    - GIT_COMMITTER_EMAIL=nakajimashouhei@gmail.com
    - GIT_AUTHOR_NAME=s-nakajima
    - GIT_AUTHOR_EMAIL=nakajimashouhei@gmail.com

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - travis_wait . tools/build/plugins/cakephp/travis/pre.sh
  - . tools/build/plugins/cakephp/travis/environment.sh

script:
  - . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always

